-- Désactiver temporairement RLS pour tester
ALTER TABLE articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_logs DISABLE ROW LEVEL SECURITY;
