// vercel-build.js
// Inject VITE_API_BASE into runtime-config.js before Vite build when deploying on Vercel.
import { writeFileSync } from 'node:fs'

const apiBase = process.env.VITE_API_BASE || './api.php'
const content = `// Auto-generated by vercel-build.js
// Sets the runtime API base used by legacy pages (admin.html, database.js)
window.API_BASE_URL = window.API_BASE_URL || ${JSON.stringify(apiBase)};
`

try {
  writeFileSync(new URL('./runtime-config.js', import.meta.url), content, { encoding: 'utf8' })
  console.log('✅ runtime-config.js generated with API base:', apiBase)
} catch (err) {
  console.error('❌ Failed to write runtime-config.js', err)
  process.exit(1)
}
