-- ============================================================
-- Base de données MTACMN - PostgreSQL pour Supabase
-- Ministère des Transports, Aviation Civile & Météorologie Nationale
-- ============================================================

-- Extension pour les UUID et la recherche plein texte
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================================
-- Table des articles
-- ============================================================
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    date VARCHAR(50) NOT NULL,
    categorie VARCHAR(50) CHECK (categorie IN ('Transports', 'Aviation Civile', 'Météorologie')) NOT NULL,
    resume TEXT NOT NULL,
    contenu TEXT,
    image VARCHAR(500),
    imageKey VARCHAR(100),
    une BOOLEAN DEFAULT FALSE,
    statut VARCHAR(20) CHECK (statut IN ('Brouillon', 'Publié')) DEFAULT 'Brouillon',
    vues BIGINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index pour les articles
CREATE INDEX IF NOT EXISTS idx_articles_categorie ON articles(categorie);
CREATE INDEX IF NOT EXISTS idx_articles_statut ON articles(statut);
CREATE INDEX IF NOT EXISTS idx_articles_une ON articles(une);
CREATE INDEX IF NOT EXISTS idx_articles_date ON articles(date);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON articles(created_at);
CREATE INDEX IF NOT EXISTS idx_articles_recentes ON articles(statut, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_categorie_statut ON articles(categorie, statut);
CREATE INDEX IF NOT EXISTS idx_articles_une_statut ON articles(une, statut);

-- Index pour la recherche plein texte
CREATE INDEX IF NOT EXISTS ft_articles_search ON articles USING gin(titre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ft_articles_resume_search ON articles USING gin(resume gin_trgm_ops);

-- Trigger pour mettre à jour updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_articles_updated_at 
    BEFORE UPDATE ON articles 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Table des paramètres du site
-- ============================================================
CREATE TABLE IF NOT EXISTS settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger pour mettre à jour updated_at
CREATE TRIGGER update_settings_updated_at 
    BEFORE UPDATE ON settings 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Table des utilisateurs
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) CHECK (role IN ('Admin', 'Super Admin', 'Editeur')) DEFAULT 'Editeur',
    actif BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index pour les utilisateurs
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_actif ON users(actif);

-- ============================================================
-- Table pour les logs des modifications
-- ============================================================
CREATE TABLE IF NOT EXISTS article_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT REFERENCES articles(id) ON DELETE CASCADE,
    action VARCHAR(20) CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    ancienne_valeur JSONB,
    nouvelle_valeur JSONB,
    utilisateur VARCHAR(50),
    date_action TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index pour les logs
CREATE INDEX IF NOT EXISTS idx_article_logs_article_id ON article_logs(article_id);
CREATE INDEX IF NOT EXISTS idx_article_logs_date_action ON article_logs(date_action);

-- ============================================================
-- Vues pour les requêtes fréquentes
-- ============================================================

-- Vue pour les articles publiés uniquement
CREATE OR REPLACE VIEW v_articles_publies AS
SELECT 
    id, titre, date, categorie, resume, contenu, image, imageKey, une, vues, created_at, updated_at
FROM articles 
WHERE statut = 'Publié'
ORDER BY created_at DESC;

-- Vue pour les statistiques des articles
CREATE OR REPLACE VIEW v_articles_stats AS
SELECT 
    categorie,
    COUNT(*) as total,
    SUM(vues) as total_vues,
    COUNT(CASE WHEN statut = 'Publié' THEN 1 END) as publies,
    COUNT(CASE WHEN statut = 'Brouillon' THEN 1 END) as brouillons
FROM articles 
GROUP BY categorie;

-- ============================================================
-- Politiques de sécurité RLS (Row Level Security)
-- ============================================================

-- Activer RLS sur les tables
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_logs ENABLE ROW LEVEL SECURITY;

-- Politiques pour la table articles (lecture publique)
CREATE POLICY "Les articles publiés sont visibles par tous" ON articles
    FOR SELECT USING (statut = 'Publié');

CREATE POLICY "Les administrateurs peuvent voir tous les articles" ON articles
    FOR ALL USING (
        auth.jwt() ->> 'role' IN ('Admin', 'Super Admin')
    );

-- Politiques pour la table settings (lecture publique, écriture admin)
CREATE POLICY "Tout le monde peut voir les settings" ON settings
    FOR SELECT USING (true);

CREATE POLICY "Les administrateurs peuvent modifier les settings" ON settings
    FOR ALL USING (
        auth.jwt() ->> 'role' IN ('Admin', 'Super Admin')
    );

-- ============================================================
-- Insertion des données initiales
-- ============================================================

-- Insertion des paramètres par défaut
INSERT INTO settings (key, value) VALUES
('siteName', 'Ministère des Transports, de l''Aviation Civile et de la Météorologie Nationale'),
('sigle', 'MTACMN'),
('ministre', 'Mme Fatimé Goukouni Weddeye'),
('secretaireGeneral', 'Dihoulné Laurent'),
('president', 'Maréchal Mahamat Idriss Déby Itno'),
('adresse', 'N''Djaména, République du Tchad'),
('telephone', '+235 22 51 44 92'),
('email', 'contact@transports.gouv.td'),
('siteOfficiel', 'transports.gouv.td'),
('bp', 'BP 578')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Insertion de l'utilisateur administrateur par défaut
-- Note: Le mot de passe devra être hashé côté application
INSERT INTO users (username, email, password, role, actif) VALUES 
('admin', 'admin@transports.gouv.td', '$2y$10$abcdefghijklmnopqrstuvwxzA1B2C3D4E5F6G7H8I9JkLmNoPqRsTuVwXyZ', 'Super Admin', TRUE)
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;

-- Insertion des articles initiaux
INSERT INTO articles (titre, date, categorie, resume, contenu, image, imageKey, une, statut, vues) VALUES 
('Audit OACI : La ministre évalue les préparatifs à l''aéroport Hassan Djamous', '21 mars 2026', 'Aviation Civile', 'La ministre Fatimé Goukouni Weddeye a effectué une visite à l''Aéroport international Hassan Djamous à quelques jours d''un audit international de l''OACI en matière de sûreté aérienne.', 'La ministre des Transports, de l''Aviation civile et de la Météorologie nationale, Fatimé Goukouni Weddeye, a effectué ce samedi 21 mars une visite à l''Aéroport international Hassan Djamous. Cette descente sur le terrain visait à galvaniser les équipes et à s''assurer de la pleine préparation avant l''audit OACI. La piste d''atterrissage a bénéficié d''une réhabilitation complète avec installation de nouveaux équipements de sécurité modernisés. Le ministère entend se conformer à toutes les normes internationales de l''Organisation de l''Aviation Civile Internationale.', 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80', 'article_1', TRUE, 'Publié', 1240),

('Semaine Nationale de la Météorologie 2026 : « Observer aujourd''hui pour protéger demain »', '24 mars 2026', 'Météorologie', 'L''ANAM a lancé officiellement la Semaine nationale de la météorologie (SENAMET) sous le thème « Observer aujourd''hui et protéger demain », avec le soutien de partenaires internationaux.', 'Le ministère des Transports, à travers l''Agence nationale de la météorologie (ANAM), a lancé officiellement la Semaine nationale de la météorologie (SENAMET). L''objectif est de sensibiliser les populations et de mobiliser des ressources pour moderniser le réseau d''observation météorologique. Les activités comprennent des panels et ateliers avec l''appui du PAM, la Banque mondiale, le PNUD et l''OMM.', 'https://images.unsplash.com/photo-1504608524841-42584120d238?w=800&q=80', 'article_2', FALSE, 'Publié', 876),

('Normes ASSA-AC : Atelier de vulgarisation de la réglementation aéronautique CEMAC', '16 février 2026', 'Aviation Civile', 'Atelier de vulgarisation des normes communautaires de l''ASSA-AC au Centre CIFOP de Farcha pour renforcer la sécurité du transport aérien national.', 'Le Secrétaire général Dihoulne Laurent a présidé l''atelier de vulgarisation de la réglementation communautaire de l''Agence de Supervision de la Sécurité Aérienne en Afrique Centrale (ASSA-AC). Cet atelier vise à renforcer la compréhension et l''application effective des normes aéronautiques communautaires de la zone CEMAC par les acteurs de l''aviation civile tchadienne.', 'https://images.unsplash.com/photo-1549827028-c4efe5b02f3e?w=800&q=80', 'article_3', FALSE, 'Publié', 543),

('Transports : Évaluation stratégique du programme présidentiel — Chantier 8', '2 mars 2026', 'Transports', 'Le Premier ministre Allah Maye Halina a présidé une réunion d''évaluation du volet transport du programme présidentiel, couvrant le désenclavement et la modernisation des infrastructures.', 'La réunion a évalué l''état d''avancement des projets prioritaires : modernisation des infrastructures routières et aéroportuaires, le projet de voie ferrée Tchad–Cameroun, le développement des ports secs à Moundou et Amdjarass, et le renforcement des partenariats avec les compagnies aériennes internationales.', 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&q=80', 'article_4', FALSE, 'Publié', 412),

('Sécurité routière : Lancement du programme « Ambassadeurs routiers »', '15 janvier 2026', 'Transports', 'Le ministère lance le programme des ambassadeurs routiers pour la vulgarisation du code de la route et l''amélioration de la sécurité sur les grands axes nationaux.', 'Dans le cadre du renforcement de la sécurité routière, le ministère a lancé le programme des « ambassadeurs routiers » pour vulgariser le code de la route et aménager des aires de repos sur les grands axes.', 'https://images.unsplash.com/photo-1555952517-2e845d1b5c1a?w=800&q=80', 'article_5', FALSE, 'Brouillon', 0);

-- ============================================================
-- Fonctions utiles
-- ============================================================

-- Fonction pour incrémenter les vues
CREATE OR REPLACE FUNCTION incrementer_vues(article_id_param BIGINT)
RETURNS VOID AS $$
BEGIN
    UPDATE articles 
    SET vues = vues + 1 
    WHERE id = article_id_param;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Configuration terminée
-- ============================================================
